name: Basic Tests

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:

  run_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

        
    steps:

      # Set-up dependencies
      - name: Check-out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for tags to be fetched; see https://github.com/actions/checkout/issues/290      

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Poetry
        shell: bash -l {0}
        run: |
          python -m pip install poetry==1.6.1


      # Install the project (we need some of the tools installed here for liniting etc)
      - name: Install the project
        shell: bash -l {0}
        run: poetry install --no-interaction --all-extras

      - name: Run tests
        shell: bash -l {0}
        run: |
          poetry run pytest
